#!/bin/sh

{
    fake_control_header 'g++'

    fake_control_package foo all '${dh-builtusing:gPP}'

} > debian/control

$tested_command

check_substvar foo gPP gcc-defaults

dh_gencontrol

check_control foo gcc-defaults
