#!/bin/sh

{
    fake_control_header 'cpp, gcc'

    fake_control_package foo all '${dh-builtusing:cpp}, ${dh-builtusing:gcc}'

} > debian/control

$tested_command

check_substvar foo cpp gcc-defaults
check_substvar foo gcc gcc-defaults

fakeroot dh_gencontrol

check_control foo gcc-defaults
